#!/usr/bin/env bash
# This script displays "To infinity and beyond" and handles SIGTERM signals
trap 'echo "I am invincible!!!"' TERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

